# Generated by Django 3.0.5 on 2020-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=60)),
                ('api_secret_key', models.CharField(max_length=60)),
                ('access_token', models.CharField(max_length=60)),
                ('access_token_secret', models.CharField(max_length=60)),
            ],
        ),
    ]
