# Generated by Django 3.0.5 on 2020-05-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttweets_app', '0003_delete_api_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=60)),
                ('access_token_secret', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'User_access_tokens',
            },
        ),
        migrations.AlterModelOptions(
            name='app_credentials',
            options={'verbose_name_plural': 'App_Credentials'},
        ),
    ]
