# Generated by Django 3.0.5 on 2020-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttweets_app', '0004_auto_20200511_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_tokens',
            name='api_key',
            field=models.CharField(default='hgvnbjm', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access_tokens',
            name='api_secret_key',
            field=models.CharField(default='jhgjiukf', max_length=60),
            preserve_default=False,
        ),
    ]
